### ISSUE TITLE
support for sumo

### ISSUE THREAD

**Issue by chillking2** [gpanders/meta-scipy#10]
Hi,

is it also possible to support sumo?
Does anyone know what I have to change/add to get it installed with sumo?

Thanks!

**Comment by gpanders** [comment]
To add sumo compatibility, modify the file `conf/layer.conf` and change the line

```
LAYERSERIES_COMPAT_meta-scipy = "warrior thud zeus dunfell"
```

to

```
LAYERSERIES_COMPAT_meta-scipy = "sumo warrior thud zeus dunfell"
```

**Comment by chillking2** [comment]
Thanks for your answer, now I know why this packages was made for newer versions. 
The next error says `scikit-image 0.16+ supports only Python 3.6 and above` and sumo comes with Python 3.5.5. 

So I guess I need an older version of scipy or a newer version of python (which I already tried but failed). 

Anyway, thanks for your help! I guess that's another problem, so this can be closed.

**Comment by gpanders** [comment]
Yea unfortunately the current state of the repo only targets scipy 1.3.3. I'm not sure how difficult it would be to build for an older version.

Best of luck with whatever you decide to do.
