### ISSUE TITLE
Add hardknott to LAYERSERIES_COMPAT

### ISSUE THREAD

**Issue by zboszor** [gpanders/meta-scipy#18]
Yocto master has changed the distro name from **gatesgarth** to **hardknott**, please add the latter to  `LAYERSERIES_COMPAT_meta-scipy` in `layer.conf` to keep compatibility.

**Comment by gpanders** [comment]
There's a little more than that that needs to be done with a new series.

First, we need to bump the SciPy version to whatever the latest is around the time the new series is released (1.6.2 is most recent release as of this writing) and then of course we need to make sure that it build successfully in the new layer.

If you want to see this done sooner, then please take a stab at doing that yourself and then making a PR if everything works. It will take me a bit longer to do it myself.

**Comment by zboszor** [comment]
I think the two issues are orthogonal.

I was testing your layer with Yocto master recently (then still named "gatesgarth" but way ahead of the actual Gatesgarth version) with an ImageAI recipe that runtime-depends on python3-scipy.

**Comment by gpanders** [comment]
I added hardknott on `master`.
