### ISSUE TITLE
Problem with petalinux 2019.1 and CMake (lapack)

### ISSUE THREAD

**Issue by ChristianG1984** [gpanders/meta-scipy#8]
Hello,

I tried to integrate your latest stable release of that layer into my petalinux image. For this process, I used this guide: https://www.zachpfeffer.com/single-post/Add-a-Yocto-Layer-to-a-PetaLinux-Project-and-Build-a-Recipe-in-the-Layer-with-PetaLinux-Tools

After that, I tweaked the things, how they were described in the README.md

So far, so good. But then, the build fails, when it comes to the "do_configure" stage of the "lapack" package.

This is the Log output of that process:

    DEBUG: Executing shell function do_configure
    -- The Fortran compiler identification is GNU 8.2.0
    -- The C compiler identification is GNU 8.2.0
    -- Check for working Fortran compiler: /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gfortran
    -- Check for working Fortran compiler: /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gfortran  -- works
    -- Detecting Fortran compiler ABI info
    -- Detecting Fortran compiler ABI info - done
    -- Checking whether /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gfortran supports Fortran 90
    -- Checking whether /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gfortran supports Fortran 90 -- yes
    -- Check for working C compiler: /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gcc
    -- Check for working C compiler: /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Setting build type to 'Release' as none was specified.
    -- Looking for Python greater than 2.6 - 
    -- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2.7")
    -- No suitable Python version found, so skipping summary tests.
    -- Build tests: OFF
    -- Reducing RELEASE optimization level to O2
    -- Looking for Fortran NONE - found
    -- Looking for Fortran INT_CPU_TIME - found
    -- Looking for Fortran EXT_ETIME - not found
    -- Looking for Fortran EXT_ETIME_ - not found
    -- Looking for Fortran INT_ETIME - found
    -- --> Will use second_INT_ETIME.f and dsecnd_INT_ETIME.f as timing function.
    -- Build deprecated routines: OFF
    -- Build single precision real: ON
    -- Build double precision real: ON
    -- Build single precision complex: ON
    -- Build double precision complex: ON
    -- Using supplied NETLIB BLAS implementation
    -- CBLAS enable
    -- Detecting Fortran/C Interface
    -- Detecting Fortran/C Interface - Failed to load sample executable
    -- Verifying Fortran/C Compiler Compatibility
    -- Verifying Fortran/C Compiler Compatibility - Failed
    CMake Error at /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface.cmake:383 (message):
      The Fortran compiler:

        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gfortran

      and the C compiler:

        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gcc

      failed to compile a simple test project using both languages.  The output
      was:

        Change Dir: /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC
        
        Run Build Command:"make" "VerifyFortranC"
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -H/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify -B/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC --check-build-system CMakeFiles/Makefile.cmake 0
        make -f CMakeFiles/Makefile2 VerifyFortranC
        make[1]: Entering directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -H/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify -B/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC --check-build-system CMakeFiles/Makefile.cmake 0
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_progress_start /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC/CMakeFiles 5
        make -f CMakeFiles/Makefile2 CMakeFiles/VerifyFortranC.dir/all
        make[2]: Entering directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        make -f CMakeFiles/VerifyFortran.dir/build.make CMakeFiles/VerifyFortran.dir/depend
        make[3]: Entering directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        cd /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC && /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC/CMakeFiles/VerifyFortran.dir/DependInfo.cmake
        Scanning dependencies of target VerifyFortran
        make[3]: Leaving directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        make -f CMakeFiles/VerifyFortran.dir/build.make CMakeFiles/VerifyFortran.dir/build
        make[3]: Entering directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        [ 20%] Building Fortran object CMakeFiles/VerifyFortran.dir/VerifyFortran.f.o
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gfortran   -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot  -I/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC  -O2 -DNDEBUG -O2   -c /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify/VerifyFortran.f -o CMakeFiles/VerifyFortran.dir/VerifyFortran.f.o
        f951: Warning: command line option '-Wformat=1' is valid for C/C++/ObjC/ObjC++ but not for Fortran
        f951: Warning: command line option '-Wformat-security' is valid for C/C++/ObjC/ObjC++ but not for Fortran
        [ 40%] Linking Fortran static library libVerifyFortran.a
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -P CMakeFiles/VerifyFortran.dir/cmake_clean_target.cmake
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_link_script CMakeFiles/VerifyFortran.dir/link.txt --verbose=1
        arm-xilinx-linux-gnueabi-ar qc libVerifyFortran.a  CMakeFiles/VerifyFortran.dir/VerifyFortran.f.o
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-ranlib libVerifyFortran.a
        make[3]: Leaving directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        [ 40%] Built target VerifyFortran
        make -f CMakeFiles/VerifyFortranC.dir/build.make CMakeFiles/VerifyFortranC.dir/depend
        make[3]: Entering directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        cd /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC && /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC/CMakeFiles/VerifyFortranC.dir/DependInfo.cmake
        Scanning dependencies of target VerifyFortranC
        make[3]: Leaving directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        make -f CMakeFiles/VerifyFortranC.dir/build.make CMakeFiles/VerifyFortranC.dir/build
        make[3]: Entering directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        [ 60%] Building C object CMakeFiles/VerifyFortranC.dir/main.c.o
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gcc  -I/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0=/usr/src/debug/lapack/3.8.0-r0 -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot= -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native=   -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot -DNDEBUG   -o CMakeFiles/VerifyFortranC.dir/main.c.o   -c /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify/main.c
        [ 80%] Building C object CMakeFiles/VerifyFortranC.dir/VerifyC.c.o
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gcc  -I/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0=/usr/src/debug/lapack/3.8.0-r0 -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot= -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native=   -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot -DNDEBUG   -o CMakeFiles/VerifyFortranC.dir/VerifyC.c.o   -c /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/share/cmake-3.12/Modules/FortranCInterface/Verify/VerifyC.c
        [100%] Linking C executable VerifyFortranC
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/cmake -E cmake_link_script CMakeFiles/VerifyFortranC.dir/link.txt --verbose=1
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/arm-xilinx-linux-gnueabi-gcc  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0=/usr/src/debug/lapack/3.8.0-r0 -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot= -fdebug-prefix-map=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native=   -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot -DNDEBUG  -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now CMakeFiles/VerifyFortranC.dir/main.c.o CMakeFiles/VerifyFortranC.dir/VerifyC.c.o  -o VerifyFortranC libVerifyFortran.a -lgfortran -lm -lm 
        /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/recipe-sysroot-native/usr/bin/arm-xilinx-linux-gnueabi/../../libexec/arm-xilinx-linux-gnueabi/gcc/arm-xilinx-linux-gnueabi/8.2.0/ld: CMakeFiles/VerifyFortranC.dir/main.c.o: in function `main':
        /usr/share/cmake-3.12/Modules/FortranCInterface/Verify/main.c:14: undefined reference to `VerifyFortran'
        collect2: error: ld returned 1 exit status
        make[3]: *** [CMakeFiles/VerifyFortranC.dir/build.make:103: VerifyFortranC] Error 1
        make[3]: Leaving directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/VerifyFortranC.dir/all] Error 2
        make[2]: Leaving directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        make[1]: *** [CMakeFiles/Makefile2:88: CMakeFiles/VerifyFortranC.dir/rule] Error 2
        make[1]: Leaving directory '/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/FortranCInterface/VerifyC'
        make: *** [Makefile:121: VerifyFortranC] Error 2
        
    Call Stack (most recent call first):
      CBLAS/CMakeLists.txt:9 (FortranCInterface_VERIFY)

    -- Configuring incomplete, errors occurred!
    See also "/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/CMakeOutput.log".
    See also "/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/build/CMakeFiles/CMakeError.log".
    WARNING: /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/temp/run.do_configure.3356:1 exit 1 from 'cmake -G 'Unix Makefiles' -DCMAKE_MAKE_PROGRAM=make $oecmake_sitefile /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/lapack-3.8.0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=bin -DCMAKE_INSTALL_SBINDIR:PATH=sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_DATAROOTDIR:PATH=share -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE=/home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/toolchain.cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 -DBUILD_SHARED_LIBS=ON ${PACKAGECONFIG_CONFARGS} -DCBLAS=ON -Wno-dev'
    ERROR: Function failed: do_configure (log file is located at /home/local/volume-data/bosens/build/tmp/work/cortexa9t2hf-neon-xilinx-linux-gnueabi/lapack/3.8.0-r0/temp/log.do_configure.3356)

Do you know, why that happened and how it can be fixed?

Kind regards,
Christian

**Comment by gpanders** [comment]
That is the error that [the CMake patch](https://github.com/gpanders/meta-scipy/blob/master/recipes-devtools/cmake/cmake-native_%25.bbappend) addresses. Can you make sure that patch is being applied properly?

**Comment by ChristianG1984** [comment]
Thank you for the reply!
I also thought, it could be a problem with the patch. (At first, I thought, it should be applied automatically within the whole process.)
I will try to check that.

**Comment by gpanders** [comment]
> At first, I thought, it should be applied automatically within the whole process.

It should be, but it's possible that PetaLinux is either not applying it for some reason or maybe it uses an older version of CMake that the patch does not apply cleanly to (although if this were the case it should fail with an error and tell you).

**Comment by ChristianG1984** [comment]
I figured out, what the reason for the problem was.
PetaLinux prevented any modification of "cmake-native" and only showed a discreet _warning_ about that, but continued with the rest, which led to that error then.

Due to this problem description (https://forums.xilinx.com/t5/Embedded-Linux/Petalinux-2017-1-do-fetch-sig-is-computed-to-be/td-p/768195), the solution was to unlock the cmake-native package by adding the line `SIGGEN_UNLOCKED_RECIPES += "cmake-native"` into the file `/project-spec/meta-user/conf/petalinuxbsp.conf`.

And just to make sure, I cleaned any cached stuff with `petalinux-build -c cmake-native -x distclean` and did a `petalinux-build` again.
Then, it compiled flawlessly. :-)

(Maybe, you can put a hint about that possible problem for other PetaLinux users into the README.md or insert a link to this solution.)

Best regards,
Christian

**Comment by gpanders** [comment]
Glad to hear you figured it out!

> Maybe, you can put a hint about that possible problem for other PetaLinux users into the README.md or insert a link to this solution.

I look forward to reviewing your pull request :)
